const TARIFFS=Object.freeze([
  {id:'start',name:'Start',monthlyRub:990,monthlyEnergy:8000,description:'Базовые инструменты для знакомства',features:['Основные режимы','Стандартная очередь']},
  {id:'creator',name:'Creator',monthlyRub:2490,monthlyEnergy:25000,description:'Для регулярного создания контента',features:['Все основные инструменты','Расширенные настройки','Приоритетная очередь'],recommended:true},
  {id:'pro',name:'Pro',monthlyRub:4990,monthlyEnergy:60000,description:'Для интенсивной работы и команд',features:['Продвинутые режимы','Высокий приоритет','Расширенные лимиты']},
  {id:'studio',name:'Studio',monthlyRub:9990,monthlyEnergy:150000,description:'Для студийного процесса',features:['Командный workflow','Максимальный приоритет','Расширенное управление']}
]);
const ENERGY_TOPUP_CONFIG=Object.freeze({minRub:100,maxRub:100000,energyPerRub:10,bonusThresholds:[{minRub:5000,percent:20},{minRub:2500,percent:15},{minRub:1000,percent:10},{minRub:500,percent:5},{minRub:0,percent:0}]});
const energyIcon=()=>'<svg class="energy-icon" aria-hidden="true"><use href="#zap"></use></svg>';
const numberFormat=n=>Number(n).toLocaleString('ru-RU');
const formatEnergy=n=>`${numberFormat(n)} ⚡`;
const energyHtml=n=>`${numberFormat(n)} ${energyIcon()}`;
const topupQuote=rub=>{const amount=Math.max(ENERGY_TOPUP_CONFIG.minRub,Math.min(ENERGY_TOPUP_CONFIG.maxRub,Math.round(Number(rub)||0)));const bonusPercent=ENERGY_TOPUP_CONFIG.bonusThresholds.find(t=>amount>=t.minRub).percent;const baseEnergy=amount*ENERGY_TOPUP_CONFIG.energyPerRub;const bonusEnergy=Math.round(baseEnergy*bonusPercent/100);return{rub:amount,baseEnergy,bonusPercent,bonusEnergy,finalEnergy:baseEnergy+bonusEnergy}};
const minimumRubForEnergy=energy=>{for(let rub=ENERGY_TOPUP_CONFIG.minRub;rub<=ENERGY_TOPUP_CONFIG.maxRub;rub++)if(topupQuote(rub).finalEnergy>=Math.max(0,energy))return rub;return ENERGY_TOPUP_CONFIG.maxRub};
const monthlyTariffCredit=tariffId=>TARIFFS.find(t=>t.id===tariffId)?.monthlyEnergy||0;
const pages=['dashboard','idea','video','image','editor','projects','assistant','balance','history','profile','settings','subscription','payments','notifications','auth','onboarding'];
const costs={economy:800,optimal:1300,maximum:3050};
let balance=Number(localStorage.getItem('konteno_balance')||localStorage.getItem('konteno_tokens'))||38000;
let duration=5,quality='optimal',imageData='',works=[],topupAmount=1000,checkoutBusy=false,lastFocus=null,pendingCreation=null,toastTimer;
try{works=JSON.parse(localStorage.getItem('konteno_works')||'[]')}catch{works=[]}
const el=id=>document.getElementById(id);
const escapeHtml=value=>{const n=document.createElement('div');n.textContent=String(value||'');return n.innerHTML};
const currentPrice=()=>Math.ceil((costs[quality]*(duration/5))/50)*50;
function sync(){['headerBalance','studioBalance','miniBalance','bigBalance','dashboardBalance','homeBalance'].forEach(id=>{if(el(id))el(id).innerHTML=energyHtml(balance)});if(el('price'))el('price').innerHTML=energyHtml(currentPrice());if(el('priceBtn'))el('priceBtn').innerHTML=energyHtml(currentPrice());localStorage.setItem('konteno_balance',String(balance));document.querySelectorAll('[data-energy]').forEach(n=>n.innerHTML=energyHtml(n.dataset.energy))}
function notify(message){el('toast').textContent=message;el('toast').classList.remove('hide');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').classList.add('hide'),3500)}
function selectTheme(theme){localStorage.setItem('konteno_theme_preference',theme);document.querySelectorAll('[data-theme]').forEach(button=>{const active=button.dataset.theme==='light';button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});if(theme==='dark')notify('Тёмная тема скоро. Пока сохраняем безопасную светлую тему.')}
function openProfile(){openStudio('profile')}
function goHome(){closeModal();el('studio').style.display='none';el('landing').style.display='block';el('top').style.display='';history.pushState({},'',location.pathname);scrollTo(0,0)}
function openStudio(page='dashboard',push=true){el('landing').style.display='none';el('top').style.display='none';el('studio').style.display='block';showPage(page,push)}
function showPage(id,push=true){if(!pages.includes(id))id='dashboard';document.querySelectorAll('.page').forEach(n=>n.classList.add('hide'));el(id).classList.remove('hide');document.querySelectorAll('[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===id));if(id==='projects')renderWorks();if(id==='history')renderTransactions();if(id==='balance')renderPurchase();if(id==='subscription')renderTariffs();if(push)history.pushState({page:id},'','#'+id);sync();scrollTo(0,0)}
function continuePrompt(){const value=el('homePrompt').value.trim();if(!value)return notify('Сначала опиши свою идею');el('assistantInput').value=value;showPage('assistant');assistantGo()}
function startTask(text){openStudio('assistant');el('assistantInput').value=text;el('assistantInput').focus()}
function setIdea(text){el('homePrompt').value=text;el('homePrompt').focus()}
function pickWorkspaceOption(node){node.parentElement.querySelectorAll('button').forEach(button=>button.classList.remove('sel'));node.classList.add('sel')}
function previewWorkspaceFile(event,targetId){const file=event.target.files[0];if(!file)return;el(targetId).textContent=file.name;el(targetId).dataset.ready='true'}
function addEditorAction(text){const input=el('editorPrompt');input.value+=(input.value?'. ':'')+text;input.focus()}
function runToolDemo(type,cost){const prompt=el(type==='image'?'imagePrompt':'editorPrompt').value.trim();if(!prompt)return notify(type==='image'?'Опиши изображение':'Опиши, что нужно изменить');if(type==='editor'&&!el('editorFile').dataset.ready)return notify('Сначала загрузи исходный файл');if(balance<cost){pendingCreation={prompt,creationType:type};sessionStorage.setItem('konteno_pending_creation',JSON.stringify(pendingCreation));showInsufficient(cost);return}balance-=cost;works.unshift({title:type==='image'?'Созданное изображение':'Результат редактора',prompt,cost,image:'',date:new Date().toLocaleString('ru-RU')});localStorage.setItem('konteno_works',JSON.stringify(works.slice(0,20)));sync();notify(type==='image'?'Демо-изображение создано и сохранено':'Демо-правка применена и сохранена')}
function previewFile(event){const file=event.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)return notify('Выбери JPG, PNG или WEBP до 15 МБ');const reader=new FileReader();reader.onload=()=>{imageData=reader.result;el('upload').innerHTML=`<img src="${imageData}" alt="Загруженное фото"><input type="file" accept="image/jpeg,image/png,image/webp" aria-label="Заменить фото" onchange="previewFile(event)">`};reader.readAsDataURL(file)}
function addPrompt(text){el('motion').value+=(el('motion').value?'. ':'')+text;el('motion').focus()}
function pickDuration(node,value){duration=value;document.querySelectorAll('.segments button').forEach(n=>n.classList.remove('sel'));node.classList.add('sel');sync()}
function pickQuality(node,value){quality=value;document.querySelectorAll('.qualities button').forEach(n=>n.classList.remove('sel'));node.classList.add('sel');sync()}
function preserveCreation(){pendingCreation={prompt:el('motion').value,duration,quality,creationType:'photo-video',hasUpload:Boolean(imageData)};sessionStorage.setItem('konteno_pending_creation',JSON.stringify(pendingCreation))}
function confirmGeneration(){if(!imageData)return notify('Сначала загрузи фото');if(el('motion').value.trim().length<3)return notify('Опиши движение');const price=currentPrice();if(balance<price){preserveCreation();showInsufficient(price);return}openModal('Создать видео?',`<div class="modalrow"><span>Длительность</span><b>${duration} сек.</b></div><div class="modalrow"><span>Режим</span><b>${quality==='optimal'?'Оптимально':quality==='economy'?'Выгодно':'Максимум'}</b></div><div class="modalrow"><span>Стоимость</span><b>${energyHtml(price)}</b></div>`,`<button class="btn secondary" onclick="closeModal()">Назад</button><button class="btn primary" onclick="startGeneration()">Создать</button>`)}
function showInsufficient(required){const deficit=required-balance;topupAmount=minimumRubForEnergy(deficit);openModal('Недостаточно энергии',`<p>Параметры создания сохранены.</p><div class="modalrow"><span>Текущий баланс</span><b>${energyHtml(balance)}</b></div><div class="modalrow"><span>Стоимость</span><b>${energyHtml(required)}</b></div><div class="modalrow"><span>Не хватает</span><b>${energyHtml(deficit)}</b></div>`,`<button class="btn secondary" onclick="closeModal()">Назад</button><button class="btn primary" onclick="closeModal();showPage('balance')">Рассчитать пополнение</button>`)}
function openModal(title,content,actions){lastFocus=document.activeElement;el('modalTitle').textContent=title;el('modalContent').innerHTML=content;el('modalActions').innerHTML=actions;el('modal').classList.remove('hide');el('modalActions').querySelector('button')?.focus()}
function closeModal(){el('modal').classList.add('hide');lastFocus?.focus?.()}
function startGeneration(){closeModal();if(balance<currentPrice())return showInsufficient(currentPrice());balance-=currentPrice();sync();el('animateForm').classList.add('hide');el('generation').classList.remove('hide');let progress=0;el('steps').innerHTML=['Анализируем изображение','Улучшаем описание','Выбираем AI','Генерируем видео'].map(x=>`<div class="step">${x}</div>`).join('');const timer=setInterval(()=>{progress=Math.min(100,progress+15);el('pct').textContent=progress+'%';el('orb').style.setProperty('--deg',progress*3.6+'deg');if(progress===100){clearInterval(timer);setTimeout(finish,250)}},180)}
function finish(){el('generation').classList.add('hide');el('result').classList.remove('hide');if(imageData)el('resultThumb').innerHTML=`<img src="${imageData}" alt="Превью результата">`;works.unshift({title:'Оживлённое фото',prompt:el('motion').value,cost:currentPrice(),image:imageData,date:new Date().toLocaleString('ru-RU')});works=works.slice(0,20);try{localStorage.setItem('konteno_works',JSON.stringify(works))}catch{notify('Результат готов, но не сохранён: память браузера заполнена')}}
function editAgain(){el('result').classList.add('hide');el('animateForm').classList.remove('hide')}
function downloadResult(){if(!imageData)return notify('Превью пока недоступно');const a=document.createElement('a');a.href=imageData;a.download='konteno-preview.png';a.click()}
function renderWorks(){el('worksGrid').innerHTML=works.length?works.map(w=>`<article class="card work"><div class="thumb">${w.image?`<img src="${w.image}" alt="Превью работы">`:'▷'}</div><h3>${escapeHtml(w.title)}</h3><p>${escapeHtml(w.prompt)}</p><small>${escapeHtml(w.date)} · ${energyHtml(w.cost)}</small></article>`).join(''):'<div class="card empty"><h3>Проектов пока нет</h3><p>Создай первый контент — результат сохранится автоматически.</p><button class="btn primary" onclick="showPage(\'idea\')">Создать проект</button></div>'}
function renderTransactions(){const rows=works.slice(0,8).map(w=>`<div><span>Создание видео<small>${escapeHtml(w.date)}</small></span><b>−${energyHtml(w.cost)}</b></div>`);el('transactions').innerHTML=rows.length?rows.join(''):'<p>Операций пока нет.</p>'}
function tariffCard(t,account=false){return `<article class="tariff-card ${t.recommended?'recommended':''}">${t.recommended?'<span>Рекомендуем</span>':''}<h3>${t.name}</h3><div class="tariff-price"><b>${numberFormat(t.monthlyRub)} ₽</b><small>/ мес</small></div><strong class="tariff-energy">${energyHtml(t.monthlyEnergy)} <small>/ мес</small></strong><p>${t.description}</p><ul>${t.features.map(f=>`<li>✓ ${f}</li>`).join('')}</ul><button class="btn ${t.recommended?'primary':'secondary'}" onclick="${account?"notify('Подключение тарифа появится после настройки billing')":"openStudio('subscription')"}">${account?'Выбрать':'Подробнее'}</button></article>`}
function renderTariffs(){const html=TARIFFS.map(t=>tariffCard(t,true)).join('');if(el('accountTariffs'))el('accountTariffs').innerHTML=html}
function setTopupAmount(value){topupAmount=topupQuote(value).rub;renderPurchase()}
function setHomeTopupAmount(value){topupAmount=topupQuote(value).rub;renderHomeCalculator()}
function renderHomeCalculator(){const q=topupQuote(topupAmount);topupAmount=q.rub;el('homeTopupInput').min=ENERGY_TOPUP_CONFIG.minRub;el('homeTopupInput').max=ENERGY_TOPUP_CONFIG.maxRub;el('homeTopupInput').value=q.rub;el('homeTopupSlider').min=ENERGY_TOPUP_CONFIG.minRub;el('homeTopupSlider').max=ENERGY_TOPUP_CONFIG.maxRub;el('homeTopupSlider').step=1;el('homeTopupSlider').value=q.rub;el('homeBaseEnergy').innerHTML=energyHtml(q.baseEnergy);el('homeBonus').innerHTML=`+${energyHtml(q.bonusEnergy)} · ${q.bonusPercent}%`;el('homeFinalEnergy').innerHTML=energyHtml(q.finalEnergy);el('homeTopupButton').textContent=`Пополнить баланс — ${numberFormat(q.rub)} ₽`}
function openHomeTopup(){openStudio('balance');setTopupAmount(topupAmount)}
function returnToCreation(){let state={creationType:'video'};try{state=JSON.parse(sessionStorage.getItem('konteno_pending_creation')||'{}')}catch{}showPage(['image','editor'].includes(state.creationType)?state.creationType:'video')}
function renderPurchase(){const q=topupQuote(topupAmount);topupAmount=q.rub;el('topupInput').min=ENERGY_TOPUP_CONFIG.minRub;el('topupInput').max=ENERGY_TOPUP_CONFIG.maxRub;el('topupInput').value=q.rub;el('topupSlider').min=ENERGY_TOPUP_CONFIG.minRub;el('topupSlider').max=ENERGY_TOPUP_CONFIG.maxRub;el('topupSlider').step=1;el('topupSlider').value=q.rub;el('topupRange').textContent=`от ${numberFormat(ENERGY_TOPUP_CONFIG.minRub)} ₽ до ${numberFormat(ENERGY_TOPUP_CONFIG.maxRub)} ₽`;el('selectedEnergy').innerHTML=energyHtml(q.finalEnergy);el('selectedMeta').textContent=`${numberFormat(q.rub)} ₽ · бонус +${q.bonusPercent}%`;el('orderSummary').innerHTML=`<div><span>Сумма</span><b>${numberFormat(q.rub)} ₽</b></div><div><span>Базовая энергия</span><b>${numberFormat(q.baseEnergy)}</b></div><div><span>Бонус +${q.bonusPercent}%</span><b>+${numberFormat(q.bonusEnergy)}</b></div><div class="total"><span>Получишь</span><b>${energyHtml(q.finalEnergy)}</b></div><div><span>К оплате</span><b>${numberFormat(q.rub)} ₽</b></div>`;el('checkout').textContent=`Перейти к оплате — ${numberFormat(q.rub)} ₽`;el('checkoutHint').innerHTML=`На баланс поступит ${energyHtml(q.finalEnergy)}`;el('returnCreation').classList.toggle('hide',!sessionStorage.getItem('konteno_pending_creation'))}
function validatePromo(){el('promoStatus').textContent=el('promo').value.trim()?'Промокод не проверен: сервис промокодов не подключён.':'Введите промокод.'}
function checkout(){if(checkoutBusy)return;checkoutBusy=true;el('checkout').disabled=true;el('checkout').textContent='Проверяем доступность…';setTimeout(()=>{checkoutBusy=false;el('checkout').disabled=false;renderPurchase();notify('Демо-режим: платёжный провайдер не подключён. Энергия не начислена.')},500)}
function assistantGo(){const q=el('assistantInput').value.trim();if(!q)return notify('Напиши задачу для помощника');el('assistantAnswer').innerHTML=`<h3>Идея готова</h3><p>Для «${escapeHtml(q)}» начни с сильного визуального хода, затем покажи развитие и короткий финал.</p><button class="btn primary" onclick="showPage('video')">Создать видео</button>`;el('assistantAnswer').classList.remove('hide')}
selectTheme('light');document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});window.addEventListener('popstate',()=>{const p=location.hash.slice(1);p&&pages.includes(p)?openStudio(p,false):goHome()});el('landingTariffs').innerHTML=TARIFFS.map(t=>tariffCard(t)).join('');renderTariffs();renderHomeCalculator();sync();if(pages.includes(location.hash.slice(1)))openStudio(location.hash.slice(1),false);
if(typeof module!=='undefined')module.exports={TARIFFS,ENERGY_TOPUP_CONFIG,formatEnergy,topupQuote,minimumRubForEnergy,monthlyTariffCredit};
