const ENERGY_PACKAGES = Object.freeze([
  {rub:500,baseEnergy:5000,bonusPercent:5,finalEnergy:5250},
  {rub:1000,baseEnergy:10000,bonusPercent:10,finalEnergy:11000},
  {rub:2500,baseEnergy:25000,bonusPercent:15,finalEnergy:28750,label:'Популярно'},
  {rub:5000,baseEnergy:50000,bonusPercent:20,finalEnergy:60000,label:'Максимальная выгода'}
]);
const energyIcon=()=>'<svg class="energy-icon" aria-hidden="true"><use href="#zap"></use></svg>';
const numberFormat=n=>Number(n).toLocaleString('ru-RU');
const formatEnergy=n=>`${numberFormat(n)} ⚡`;
const energyHtml=n=>`${numberFormat(n)} ${energyIcon()}`;
const smartPackageIndex=(balance,required)=>{const deficit=Math.max(0,required-balance);const i=ENERGY_PACKAGES.findIndex(p=>p.finalEnergy>=deficit);return i<0?ENERGY_PACKAGES.length-1:i};
const pages=['home','animate','works','assistant','balance','history'];
const costs={economy:800,optimal:1300,maximum:3050};
let balance=Number(localStorage.getItem('konteno_balance')||localStorage.getItem('konteno_tokens'))||38000;
let duration=5,quality='optimal',imageData='',works=[],selectedPackage=1,checkoutBusy=false,lastFocus=null,pendingCreation=null,toastTimer;
try{works=JSON.parse(localStorage.getItem('konteno_works')||'[]')}catch{works=[]}
const el=id=>document.getElementById(id);
const escapeHtml=value=>{const n=document.createElement('div');n.textContent=String(value||'');return n.innerHTML};
const currentPrice=()=>Math.ceil((costs[quality]*(duration/5))/50)*50;
function sync(){['headerBalance','studioBalance','miniBalance','bigBalance'].forEach(id=>{if(el(id))el(id).innerHTML=energyHtml(balance)});if(el('price'))el('price').innerHTML=energyHtml(currentPrice());if(el('priceBtn'))el('priceBtn').innerHTML=energyHtml(currentPrice());localStorage.setItem('konteno_balance',String(balance));document.querySelectorAll('[data-energy]').forEach(n=>n.innerHTML=energyHtml(n.dataset.energy))}
function notify(message){el('toast').textContent=message;el('toast').classList.remove('hide');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').classList.add('hide'),3500)}
function themeInfo(){notify('Светлая тема активна. Тёмная тема появится позже.')}
function goHome(){closeModal();el('studio').style.display='none';el('landing').style.display='block';el('top').style.display='flex';history.pushState({},'',location.pathname);scrollTo(0,0)}
function openStudio(page='home',push=true){el('landing').style.display='none';el('top').style.display='none';el('studio').style.display='block';showPage(page,push)}
function showPage(id,push=true){if(!pages.includes(id))id='home';document.querySelectorAll('.page').forEach(n=>n.classList.add('hide'));el(id).classList.remove('hide');document.querySelectorAll('[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===id));if(id==='works')renderWorks();if(id==='history')renderTransactions();if(id==='balance')renderPurchase();if(push)history.pushState({page:id},'','#'+id);sync();scrollTo(0,0)}
function continuePrompt(){const value=el('homePrompt').value.trim();if(!value)return notify('Сначала опиши свою идею');el('assistantInput').value=value;showPage('assistant');assistantGo()}
function startTask(text){openStudio('assistant');el('assistantInput').value=text;el('assistantInput').focus()}
function previewFile(event){const file=event.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)return notify('Выбери JPG, PNG или WEBP до 15 МБ');const reader=new FileReader();reader.onload=()=>{imageData=reader.result;el('upload').innerHTML=`<img src="${imageData}" alt="Загруженное фото"><input type="file" accept="image/jpeg,image/png,image/webp" aria-label="Заменить фото" onchange="previewFile(event)">`};reader.readAsDataURL(file)}
function addPrompt(text){el('motion').value+=(el('motion').value?'. ':'')+text;el('motion').focus()}
function pickDuration(node,value){duration=value;document.querySelectorAll('.segments button').forEach(n=>n.classList.remove('sel'));node.classList.add('sel');sync()}
function pickQuality(node,value){quality=value;document.querySelectorAll('.qualities button').forEach(n=>n.classList.remove('sel'));node.classList.add('sel');sync()}
function preserveCreation(){pendingCreation={prompt:el('motion').value,duration,quality,creationType:'photo-video',hasUpload:Boolean(imageData)};sessionStorage.setItem('konteno_pending_creation',JSON.stringify(pendingCreation))}
function confirmGeneration(){if(!imageData)return notify('Сначала загрузи фото');if(el('motion').value.trim().length<3)return notify('Опиши движение');const price=currentPrice();if(balance<price){preserveCreation();showInsufficient(price);return}openModal('Создать видео?',`<div class="modalrow"><span>Длительность</span><b>${duration} сек.</b></div><div class="modalrow"><span>Режим</span><b>${quality==='optimal'?'Оптимально':quality==='economy'?'Выгодно':'Максимум'}</b></div><div class="modalrow"><span>Стоимость</span><b>${energyHtml(price)}</b></div>`,`<button class="btn secondary" onclick="closeModal()">Назад</button><button class="btn primary" onclick="startGeneration()">Создать</button>`)}
function showInsufficient(required){const deficit=required-balance;selectedPackage=smartPackageIndex(balance,required);openModal('Недостаточно энергии',`<p>Параметры создания сохранены.</p><div class="modalrow"><span>Текущий баланс</span><b>${energyHtml(balance)}</b></div><div class="modalrow"><span>Нужно</span><b>${energyHtml(required)}</b></div><div class="modalrow"><span>Не хватает</span><b>${energyHtml(deficit)}</b></div>`,`<button class="btn secondary" onclick="closeModal()">Назад</button><button class="btn primary" onclick="closeModal();showPage('balance')">Пополнить энергию</button>`)}
function openModal(title,content,actions){lastFocus=document.activeElement;el('modalTitle').textContent=title;el('modalContent').innerHTML=content;el('modalActions').innerHTML=actions;el('modal').classList.remove('hide');el('modalActions').querySelector('button')?.focus()}
function closeModal(){el('modal').classList.add('hide');lastFocus?.focus?.()}
function startGeneration(){closeModal();if(balance<currentPrice())return showInsufficient(currentPrice());balance-=currentPrice();sync();el('animateForm').classList.add('hide');el('generation').classList.remove('hide');let progress=0;el('steps').innerHTML=['Анализируем изображение','Улучшаем описание','Выбираем AI','Генерируем видео'].map(x=>`<div class="step">${x}</div>`).join('');const timer=setInterval(()=>{progress=Math.min(100,progress+15);el('pct').textContent=progress+'%';el('orb').style.setProperty('--deg',progress*3.6+'deg');if(progress===100){clearInterval(timer);setTimeout(finish,250)}},180)}
function finish(){el('generation').classList.add('hide');el('result').classList.remove('hide');if(imageData)el('resultThumb').innerHTML=`<img src="${imageData}" alt="Превью результата">`;works.unshift({title:'Оживлённое фото',prompt:el('motion').value,cost:currentPrice(),image:imageData,date:new Date().toLocaleString('ru-RU')});works=works.slice(0,20);try{localStorage.setItem('konteno_works',JSON.stringify(works))}catch{notify('Результат готов, но не сохранён: память браузера заполнена')}}
function editAgain(){el('result').classList.add('hide');el('animateForm').classList.remove('hide')}
function downloadResult(){if(!imageData)return notify('Превью пока недоступно');const a=document.createElement('a');a.href=imageData;a.download='konteno-preview.png';a.click()}
function renderWorks(){el('worksGrid').innerHTML=works.length?works.map(w=>`<article class="card work"><div class="thumb">${w.image?`<img src="${w.image}" alt="Превью работы">`:'▷'}</div><h3>${escapeHtml(w.title)}</h3><p>${escapeHtml(w.prompt)}</p><small>${escapeHtml(w.date)} · ${energyHtml(w.cost)}</small></article>`).join(''):'<div class="card empty"><h3>Здесь появятся твои работы</h3><p>Создай первый контент — результат сохранится автоматически.</p></div>'}
function renderTransactions(){const rows=works.slice(0,8).map(w=>`<div><span>Создание видео<small>${escapeHtml(w.date)}</small></span><b>−${energyHtml(w.cost)}</b></div>`);el('transactions').innerHTML=rows.length?rows.join(''):'<p>Операций пока нет.</p>'}
function packageCard(p,i,landing=false){return `<button class="package-card ${!landing&&i===selectedPackage?'selected':''}" ${!landing?'aria-pressed="'+(i===selectedPackage)+'"':''} onclick="${landing?`openPurchase(${i})`:`selectPackage(${i})`}">${p.label?`<span class="package-label">${p.label}</span>`:''}<strong>${numberFormat(p.rub)} ₽</strong><b>${energyHtml(p.finalEnergy)}</b><small>+${p.bonusPercent}%</small></button>`}
function renderLandingPackages(){el('landingPackages').innerHTML=ENERGY_PACKAGES.map((p,i)=>packageCard(p,i,true)).join('')}
function openPurchase(i){selectedPackage=i;openStudio('balance')}
function selectPackage(i){selectedPackage=Math.max(0,Math.min(3,i));renderPurchase()}
function renderPurchase(){el('purchasePackages').innerHTML=ENERGY_PACKAGES.map((p,i)=>packageCard(p,i)).join('');const p=ENERGY_PACKAGES[selectedPackage],bonus=p.finalEnergy-p.baseEnergy;el('packageSlider').value=selectedPackage;el('sliderOutput').textContent=numberFormat(p.rub)+' ₽';el('orderSummary').innerHTML=`<div><span>Пакет</span><b>${numberFormat(p.rub)} ₽</b></div><div><span>Базовая энергия</span><b>${numberFormat(p.baseEnergy)}</b></div><div><span>Бонус +${p.bonusPercent}%</span><b>+${numberFormat(bonus)}</b></div><div class="total"><span>Получишь</span><b>${energyHtml(p.finalEnergy)}</b></div><div><span>К оплате</span><b>${numberFormat(p.rub)} ₽</b></div>`;el('checkout').textContent=`Перейти к оплате — ${numberFormat(p.rub)} ₽`;el('checkoutHint').innerHTML=`На баланс поступит ${energyHtml(p.finalEnergy)}`;el('returnCreation').classList.toggle('hide',!sessionStorage.getItem('konteno_pending_creation'))}
function validatePromo(){el('promoStatus').textContent=el('promo').value.trim()?'Промокод не проверен: сервис промокодов не подключён.':'Введите промокод.'}
function checkout(){if(checkoutBusy)return;checkoutBusy=true;el('checkout').disabled=true;el('checkout').textContent='Проверяем доступность…';setTimeout(()=>{checkoutBusy=false;el('checkout').disabled=false;renderPurchase();notify('Демо-режим: платёжный провайдер не подключён. Энергия не начислена.')},500)}
function assistantGo(){const q=el('assistantInput').value.trim();if(!q)return notify('Напиши задачу для помощника');el('assistantAnswer').innerHTML=`<h3>Идея готова</h3><p>Для «${escapeHtml(q)}» начни с сильного визуального хода, затем покажи развитие и короткий финал.</p><button class="btn primary" onclick="showPage('animate')">Создать видео</button>`;el('assistantAnswer').classList.remove('hide')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});window.addEventListener('popstate',()=>{const p=location.hash.slice(1);p&&pages.includes(p)?openStudio(p,false):goHome()});renderLandingPackages();sync();if(pages.includes(location.hash.slice(1)))openStudio(location.hash.slice(1),false);
if(typeof module!=='undefined')module.exports={ENERGY_PACKAGES,formatEnergy,smartPackageIndex};
